# netlify.toml

[build]
  command = "npm run build"  # Replace this with your build command
  

# If your React app uses a specific Node.js version, specify it here
[build.environment]
  NODE_VERSION = "21"


